[project]
name = "computer-vision-training"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flirpy>=0.3.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "ultralytics>=8.3.160",
]
